name = "mjerred"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-03-25"
kv_namespaces = [
  {binding = "ViewCounter", id = "fb17408881bd4a84a1d3a5919389a65c"}
]
